openapi: 3.0.0
info :
  version : 1.0.0
  title : SEII_Progetto_21
  description : API del progetto per il corso di Ingegnieria del software 2 dell'Università degli studi di Trento
  
servers : 
  - url : http://localhost
  
paths :
  /species :
    get :
      description : Returns the list of all species
      parameters :
        - name : id
          in : query
          description : Specify the ID of the species to return
          schema :
            type : integer
      responses :
        '200' :
          description : succesfully returned a list of species
          content :
            application/json :
              schema :
                type : object
                properties :
                  species :
                    type : array
                    items :
                      type : object
                      properties :
                        scientific name : 
                          type : string
                        common name :
                          type : string
                        genome :
                          type : array
                          items :
                            type : string
        '400' :
          description : Invalid request
          content :
            application/json :
              schema :
                type : object
                properties :   
                  message :
                    type : string
    post:
      description: Lets a user post a new species
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                scientific name:
                  type: string
                common name :
                  type : string
                genome :
                  type : array
                  items :
                    type : string

      responses:
        '200':
          description: Successfully posted a species

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string                
      
  /genes :
    get :
      description : Returns the list of all genes
      parameters :
        - name : id
          in : query
          description : Specify the ID of the gene to return
          schema :
            type : integer
      responses : 
        '200' :
          description : succesfully returned a list of genes
          content :
            application/json :
              schema :
                type : object
                properties :
                  genes :
                    type : array
                    items : 
                      type : object
                      properties :
                        id :
                          type : string
                        biotype :
                          type : string
                        chromosome :
                          type : integer
                        strand :
                          type : integer
                        sequence :
                          type : string
                        description: 
                          type : string
                        start :
                          type : integer
                        end :
                          type : integer
                        version :
                          type : string
                        homologies :
                          type : array
                          items :
                            type : string
                        gene_tree_id : 
                          type : string
        '400' :
          description : Invalid request
          content :
            application/json :
              schema :
                type : object
                properties :   
                  message :
                    type : string
  /qanda :
    get:
      description : Returns the list of all Q&As
      parameters :
        - name : id
          in : query
          description : Specify the ID of the Q&A to return
          schema :
            type : integer
      responses :
        '200' :
          description : Succesfully returned a list of Q&As
          content :
            application/json :
              schema :
                type : object
                properties :
                  qanda :
                    type : array
                    items :
                      type : object
                      properties:
                        id:
                          type : string
                        questionAuthor :
                          type : string
                        answerAuthor :
                          type : string
                        questionText :
                          type : string
                        answerText :
                          type : string
    post:
      description: Lets a user post a new Q&A
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string

      responses:
        '200':
          description: Successfully posted a Q&A

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string