openapi: 3.0.0
info :
  version : 1.0.0
  title : SEII_Progetto_21
  description : API del progetto per il corso di Ingegnieria del software 2 dell'Università degli studi di Trento
  
servers : 
  - url : https://se-2-progetto-21-test.herokuapp.com/
  
paths :
  /species :
    get :
      description : Returns the list of all species
     
      responses :
        '200' :
          description : succesfully returned a list of species
          content :
            application/json :
              schema :
                type : object
                properties :
                  species :
                    type : array
                    items :
                      type : object
                      properties :
                        scientific name : 
                          type : string
                        common name :
                          type : string
                        genome :
                          type : array
                          items :
                            type : string
        '400' :
          description : Invalid request
          content :
            application/json :
              schema :
                type : object
                properties :   
                  message :
                    type : string

  /species/{id} :
    get :
      description : Returns a species identified by its ID
      parameters :
        - name : id
          in : query
          description : Specify the ID of the species to return
          schema :
            type : integer
      responses :
        '200' :
          description : succesfully returned a species object
          content :
            application/json :
              schema :
                type : object
                properties :
                  species :
                    type : array
                    items :
                      type : object
                      properties :
                        scientific name : 
                          type : string
                        common name :
                          type : string
                        genome :
                          type : array
                          items :
                            type : string
        '400' :
          description : Invalid request
          content :
            application/json :
              schema :
                type : object
                properties :   
                  message :
                    type : string

  /species/{id}/{gene} :
    get :
      description : Returns a gene for the species identified by its ID
      parameters :
        - name : id
          in : query
          description : Specify the ID of the species to return
          schema :
            type : integer
        - name : gene
          in : query
          description : Specify the ID the gene to return
          schema :
            type : integer
      responses :
        '200' :
          description : succesfully returned a gene object
          content :
            application/json :
              schema :
                type : object
                properties :
                  genes :
                    type : array
                    items : 
                      type : object
                      properties :
                        id :
                          type : string
                        biotype :
                          type : string
                        chromosome :
                          type : integer
                        strand :
                          type : integer
                        sequence :
                          type : string
                        description: 
                          type : string
                        start :
                          type : integer
                        end :
                          type : integer
                        version :
                          type : string
                        homologies :
                          type : array
                          items :
                            type : string
                        gene_tree_id : 
                          type : string
        '400' :
          description : Invalid request
          content :
            application/json :
              schema :
                type : object
                properties :   
                  message :
                    type : string

  /genes :
    get :
      description : Returns the list of all genes
      
      responses : 
        '200' :
          description : succesfully returned a list of genes
          content :
            application/json :
              schema :
                type : object
                properties :
                  genes :
                    type : array
                    items : 
                      type : object
                      properties :
                        id :
                          type : string
                        biotype :
                          type : string
                        chromosome :
                          type : integer
                        strand :
                          type : integer
                        sequence :
                          type : string
                        description: 
                          type : string
                        start :
                          type : integer
                        end :
                          type : integer
                        version :
                          type : string
                        homologies :
                          type : array
                          items :
                            type : string
                        gene_tree_id : 
                          type : string
        '400' :
          description : Invalid request
          content :
            application/json :
              schema :
                type : object
                properties :   
                  message :
                    type : string
    
  /genes/{id} :
    get :
      description : Returns one genes identified by its ID
      parameters :
        - name : id
          in : query
          description : Specify the ID of the gene to return
          schema :
            type : integer
      responses : 
        '200' :
          description : succesfully returned a gene object
          content :
            application/json :
              schema :
                type : object
                properties :
                  genes :
                    type : array
                    items : 
                      type : object
                      properties :
                        id :
                          type : string
                        biotype :
                          type : string
                        chromosome :
                          type : integer
                        strand :
                          type : integer
                        sequence :
                          type : string
                        description: 
                          type : string
                        start :
                          type : integer
                        end :
                          type : integer
                        version :
                          type : string
                        homologies :
                          type : array
                          items :
                            type : string
                        gene_tree_id : 
                          type : string
        '400' :
          description : Invalid request
          content :
            application/json :
              schema :
                type : object
                properties :   
                  message :
                    type : string
                    
                    
                    
  /users :
    get :
      description : Returns the list of all/one users
      responses :
        '200' :
          description : succesfully returned a list of users
          content :
            application/json :
              schema :
                type : object
                properties :
                  users :
                    type : array
                    items :
                      type : object
                      properties :
                        id : 
                          type : string
                        email :
                          type : string
                        username :
                          type : string
                        password :
                          type : string
                        admin :
                          type : boolean
                        uploadedgenes :
                          type : array
                          items :
                            type : object
                            properties :
                                usergeneid :
                                  type : string
                                approved :
                                  type : boolean
        '400' :
          description : Invalid request
          content :
            application/json :
              schema :
                type : object
                properties :   
                  message :
                    type : string
    post:
      description: Lets a user sign up
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type : object
              properties :
                id : 
                  type : string
                email :
                  type : string
                username :
                  type : string
                password :
                  type : string
      responses:
        '201':
          description: Successfully posted a user

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string                
  /users/{id} :
    get :
      description : Returns one user identified by its ID
      parameters :
        - name : id
          in : query
          description : Specify the ID of the user to return
          schema :
            type : integer
      responses :
        '200' :
          description : succesfully returned a users object
          content :
            application/json :
              schema :
                type : object
                properties :
                  users :
                    type : array
                    items :
                      type : object
                      properties :
                        id : 
                          type : string
                        email :
                          type : string
                        username :
                          type : string
                        password :
                          type : string
                        admin :
                          type : boolean
                        uploadedgenes :
                          type : array
                          items :
                            type : object
                            properties :
                                usergeneid :
                                  type : string
                                approved :
                                  type : boolean
        '400' :
          description : Invalid request
          content :
            application/json :
              schema :
                type : object
                properties :   
                  message :
                    type : string
  /users/auth :
    post:
      description: Lets a user authenticate to access more features
      parameters :
        - name : email
          in : query
          description : Specify the email of the user who wants to log in
          schema :
            type : string
        - name : password
          in : query
          description : Specify the password of the user who wants to log in
          schema :
            type : string
                
      responses:
        '200':
          description: User authenticated correctly
          content:
            application/json:
              schema:
                type: object
                properties:   
                  token:
                    type: string  

        '400':
          description: User not found or wrong password       
  /qanda :
    get:
      description : Returns the list of all Q&As
      
      responses :
        '200' :
          description : Succesfully returned a list of Q&As
          content :
            application/json :
              schema :
                type : object
                properties :
                  qanda :
                    type : array
                    items :
                      type : object
                      properties:
                        id:
                          type : string
                        questionAuthor :
                          type : string
                        answerAuthor :
                          type : string
                        questionText :
                          type : string
                        answerText :
                          type : string
    post:
      description: Lets a user post a new Q&A
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string

      responses:
        '200':
          description: Successfully posted a Q&A

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string                
  /qanda/{id} :
      parameters :
      - name : id
        in : query
        description : Specify the ID of the Q&A
        schema :
          type : integer
      get:
        description : Returns the Q&A identified by the ID
        responses :
          '200' :
            description : Succesfully returned a Q&A object
            content :
              application/json :
                schema :
                  type : object
                  properties :
                    qanda :
                      type : array
                      items :
                        type : object
                        properties:
                          id:
                            type : string
                          questionAuthor :
                            type : string
                          answerAuthor :
                            type : string
                          questionText :
                            type : string
                          answerText :
                            type : string
      delete:
        summary: DELETE
        description : Delete a specific Q&A identified by its ID
        responses:
          '201':
            description: Deleted
          '204':
            description: id not found
          '404':
            description: Unauthorized
  /qanda/answer :
    post:
      description: Lets a modder post a new answer to a question
      requestBody:
        required: true
        content:
          - name : answerText
            in : body
            description : The answer of the question
            schema :
              type : string
          - name : answerAuthor
            in : body
            description : The author of the answer
            schema :
              type : string
          - name : answerText
            in : body
            description : The answer of the question
            schema :
              type : string
      responses:
        '200':
          description: ''

        '400':
          description: no question modified
          
  /genome/compara :
    get:
      description : Compares only two species
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                species1:
                  type: string
                species2:
                  type: string
                token:
                  type: string

      responses :
        '200' :
          description : ''
          content :
            application/json :
                schema :
                  type : object
                  properties :
                    spicie1 :
                      type : string
                    genes : 
                      type : array
        '404':
          description: descriptive error
          content :
            application/json :
                schema :
                  type : object
  /genome/compara :
    get:
      description : Compares two species and a chromosome
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                species1:
                  type: string
                species2:
                  type: string
                chr:
                  type: string
                token:
                  type: string

      responses :
        '200' :
          description : ''
          content :
            application/json :
                schema :
                  type : object
                  properties :
                    spicie1 :
                      type : string
                    genes : 
                      type : array
        '404':
          description: descriptive error
          content :
            application/json :
                schema :
                  type : string
                  
  /genome/{species}/{start}/{end} :
    parameters :
      - name : species
        in : query
        description : Specify the specie
        schema :
          type : string
      - name : start
        in : query
        description : the minimum starting point for a gene
        schema :
          type : integer
      - name : end
        in : query
        description : the maximum ending point to a gene
        schema :
          type : integer
    get:
      description : gets a genom from the selected start to the selected end

      responses :
        '200' :
          description : ''
          content :
            application/json :
                schema :
                  type : object
                  properties:
                    message :
                      type : string
        '404':
          description: descriptive error
          content :
            application/json :
                schema :
                  type : object
                  properties:
                    message :
                      type : string
  /genome/{species} :
    parameters :
      - name : species
        in : query
        description : Specify the specie
        schema :
          type : string
  
    get:
      description : gets all the genome of the selected specie

      responses :
        '200' :
          description : ''
          content :
            application/json :
                schema :
                  type : object
        '404':
          description: descriptive error
          content :
            application/json :
                schema :
                  type : object