openapi: 3.0.0
info:
  version: '1.0'
  title: "Cogens OpenAPI 3.0"
  description: API for comparing different species genes.
  license:
    name: MIT
servers:
  - url: http://localhost:3000/api/v1
    description: Localhost
paths:
  /students:
    post:
      description: >-
        Creates a new student in the system.
      summary: Register a new student
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  description: 'Email address of the student'
      responses:
        '201':
          description: 'User created. Link in the Location header'
          headers:
            'Location':
              schema:
                type: string
              description: Link to the newly created student.

  /species:
    get:
      description: >-
        Gets the list of species from which the user can choose from.
      summary: View all species
      responses:
        '200':
          description: 'Collection of species'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/species'
 /species/{species_name}:
    get:
      description: >-
        Gets the list all the genes of the selected species
      summary: View all genes
      responses:
      '200':
        description: 'Collection of genes'
        content:
          application/json:
            schema:
                type: array
                items:
                  $ref: '#/components/schemas/species/{species_name}'
       '404':
        description: 'Collection of genes not found'

######################################################################VANNO BENE LE PARENTESI GRAFFE COSììììììì??
/species/{species}/{identifier}:
    get:
      description: >-
        Gets the information about the specified gene
      summary: View specified gene
      responses:
      '200':
        description: 'Info about gene'
        content:
          application/json:
            schema:
                type: array
                items:
                  $ref: '#/components/schemas/species/{species_name}/{identifier}' 
       '404':
        description: 'Collection of genes not found'

  
        /booklendings:
    post:
      description: >-
        Creates a new booklending.
      summary: Borrow a book
      responses:
        '201':
          description: 'Booklending created. Link in the Location header'
          headers:
            'Location':
              schema:
                type: string
              description: Link to the newly created booklending.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booklending'
          
components:
  schemas:
    Student:
      type: object
      required:
        - id
        - email
      properties:
        id:
          type: integer
          description: 'ID of the user'
        email:
          type: string
          description: 'Email address of the user'
    Gene:
      type: object
      required:
        - id
        - version
        - start
        - end
        - biotype
        - chromosome
        - strand
        - name
        - description

      properties:
        id:
          type: string
          description: 'Identifier of the gene'
        version:
          type: integer
          description: 'Version of the gene'
        start:
          type: integer
          description: 'Start position of the gene in the chromosome'
        end:
          type: integer
          description: 'End position of the gene in the chromosome'
        biotype:
          type: string
          description: 'Classification of a gene'
        chromosome:
          type: string
          description: 'Chromosome in which lays the gene'
        strand:
          type: integer
          description: 'DNA strand in which lays the gene'
        name:
          type: string
          description: 'Biotype of the genes'
        name:
          type: string
          description: 'Name'
        description:
          type: string
          description: 'Bioproduct of the transcript of the gene'
    Booklending:
      type: object
      required:
      - student
      - book
      properties:
        user:
          type: string
          description: 'Link to the user'
        book:
          type: integer
          description: 'Link to the book'